# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: myWeb.ci

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
 -name: instructor
 value: Santosh

steps:

- script: 
    echo "Greetings From your Instructor [ $(instructor) ]"
  displayName: greetings
- powershell: |
    Get-ChildItem -Path Env:
  displayName: print environment info
